### ISSUE TITLE
aporia

### ISSUE THREAD

**Issue by ezra1** [nim-lang/gtk2#12]
trying to get aporia up and running.  Its an issue specific to openbsd and iconv_open (openbsd uses libiconv_open, libconv*
aporia compiles, but when trying to open it I get cannot import iconv_open
I'm trying to work around it and found glib2.nim is where iconv dynlib resides, just not sure how to change it to get it work

**Comment by winksaville** [comment]
I ran into the same problem, any solution?

**Comment by ezra1** [comment]
never figured it out, moved on

**Comment by aboisvert** [comment]
FYI, this is a duplicate of https://github.com/nim-lang/gtk2/issues/12

**Comment by dom96** [comment]
This also doesn't seem to have anything to do with gtk.

**Comment by ringabout** [comment]
well it is still not fixed
