### ISSUE TITLE
gdk MASK missing?

### ISSUE THREAD

**Issue by glurp** [nim-lang/gtk2#16]
Hello,
Trying to program a draw with Nim/Gtk2, I encouter some difficulties (no demo
of Drawing area:) )

I added this in my source : 

let 
  EXPOSURE_MASK            = 0x000002
  POINTER_MOTION_MASK      = 0x000004
  POINTER_MOTION_HINT_MASK = 0x000008
  BUTTON_MOTION_MASK       = 0x000010
  BUTTON1_MOTION_MASK      = 0x000020
  BUTTON2_MOTION_MASK      = 0x000040
  BUTTON3_MOTION_MASK      = 0x000080
  BUTTON_PRESS_MASK        = 0x000100
  BUTTON_RELEASE_MASK      = 0x000200
  KEY_PRESS_MASK           = 0x000400
  KEY_RELEASE_MASK         = 0x000800
  ENTER_NOTIFY_MASK        = 0x001000
  LEAVE_NOTIFY_MASK        = 0x002000
  FOCUS_CHANGE_MASK        = 0x004000
  STRUCTURE_MASK           = 0x008000
  PROPERTY_CHANGE_MASK     = 0x010000
  VISIBILITY_NOTIFY_MASK   = 0x020000
  PROXIMITY_IN_MASK        = 0x040000
  PROXIMITY_OUT_MASK       = 0x080000
  SUBSTRUCTURE_MASK        = 0x100000
  SCROLL_MASK              = 0x200000
  TOUCH_MASK               = 0x400000
  SMOOTH_SCROLL_MASK       = 0x800000
  ALL_EVENTS_MASK          = 0xFFFFFE

then this code seem functional:
let cv=  drawing_area_new()
add_events(PWIDGET(cv),gint(EXPOSURE_MASK + BUTTON_PRESS_MASK + POINTER_MOTION_MASK + BUTTON_RELEASE_MASK + KEY_PRESS_MASK))

discard signal_connect(cv, "expose-event", SIGNAL_FUNC(exposeProc),  cv)
discard signal_connect(cv, "button-press-event", SIGNAL_FUNC(click_proc), cv)
discard signal_connect(cv, "motion-notify-event", SIGNAL_FUNC(motion_proc), cv)
discard signal_connect(cv, "button-release-event", SIGNAL_FUNC(release_proc), cv)

my complete Drawing Area test is at :
https://gist.github.com/glurp/1b9d81912a2c94e839b7

**Comment by dom96** [comment]
Are these defined in the gtk2 header files? If so, please create a PR adding them but make them 'const'.

**Comment by glurp** [comment]
Oups,
These MASK  exists in gdk2.nim.

So I PR the demo only.
